name: holocron
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5
  get_it: ^9.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/people/
    - assets/background/
